services:
  frontend:
    build: .
    container_name: clockit
    restart: unless-stopped
    networks:
      - web
    expose:
      - "3000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ytdl-frontend.rule=(Host(`your.domain`))"
      - "traefik.http.routers.ytdl-frontend.entrypoints=websecure"
      - "traefik.http.routers.ytdl-frontend.tls.certresolver=myresolver"
      - "traefik.http.services.ytdl-frontend.loadbalancer.server.port=3000"

networks:
  web:
    external: true