services:
  frontend:
    build: .
    container_name: clockit
    restart: unless-stopped
    networks:
      - web
    expose:
      - "3000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.clockit.rule=Host(`${HOST}`)"
      - "traefik.http.routers.clockit.entrypoints=websecure"
      - "traefik.http.routers.clockit.tls.certresolver=myresolver"
      - "traefik.http.services.clockit.loadbalancer.server.port=3000"

networks:
  web:
    external: true